import { useEffect,useMemo,useState } from "react";
import { useNavigate } from "react-router-dom";
import FilterBar from "../../components/common/FilterBar";
import RiskMap from "../../components/map/RiskMap";
import RegionDetailsPanel from "../../components/risk/RegionDetailsPanel";
import SelectedAreaPanel from "../../components/risk/SelectedAreaPanel";
import PopulationProfile from "../../components/villages/PopulationProfile";
import HazardBars from "../../components/risk/HazardBars";
import HistoryTimeline from "../../components/charts/HistoryTimeline";
import RainfallTrendChart from "../../components/charts/RainfallTrendChart";
import RegionHistoryPanel from "../../components/charts/RegionHistoryPanel";
import RelocationBox from "../../components/relocation/RelocationBox";
import { api } from "../../services/api";
import type { Village,VillageDetail,RelocationPlan,SafeSite,Alert,LiveHazard,LiveHazardFeed } from "../../types";
const COUNTRIES=["India"];
const INDIA_STATES=["West Bengal","Bihar","Sikkim","Odisha"];
const OFFICIALS=[
 {name:"Anushko Adhikary",email:"anushkoadhikary8918@gmail.com",phone:"8918552039"},
 {name:"Medha Mallick",email:"medha.mallick2020@gmail.com",phone:"9007564988"},
 {name:"Ayan Acharya",email:"ayanacharya06@gmail.com",phone:"9433172520"},
 {name:"Soumyadeep Palit",email:"soumyadeeppalit546@gmail.com",phone:"8697453997"},
 {name:"Prithiwi Barui",email:"prithiwibarui@gmail.com",phone:"9748069930"}
];
const SOURCE_EMAIL="mishravinit923@gmail.com";
const STORED=localStorage.getItem("rakshasetu_region")||"";
const levelRank=(v:string)=>v==="CRITICAL"?0:v==="HIGH"?1:v==="MODERATE"?2:3;
export default function Dashboard(){
 const navigate=useNavigate(); const [villages,setVillages]=useState<Village[]>([]);const [safeSites,setSafeSites]=useState<SafeSite[]>([]);const [alerts,setAlerts]=useState<Alert[]>([]);const [liveFeed,setLiveFeed]=useState<LiveHazardFeed>({updated_at:"",items:[],sources:[]});const [news,setNews]=useState<any[]>([]);const [country,setCountry]=useState("India");const [state,setStateValue]=useState(INDIA_STATES.includes(STORED)?STORED:"");const [district,setDistrict]=useState("");const [level,setLevel]=useState("");const [selectedId,setSelectedId]=useState<string|null>(null);const [detail,setDetail]=useState<VillageDetail|null>(null);const [plan,setPlan]=useState<RelocationPlan|null>(null);const [regionBestSite,setRegionBestSite]=useState<any>(null);const [loading,setLoading]=useState(true);
 const mapRegion=state||"India";
 const refreshLive=()=>api.live.hazards(mapRegion).then(setLiveFeed).catch(()=>{});
 useEffect(()=>{Promise.all([api.villages.list(),api.safeSites.list(),api.alerts.list(),api.live.hazards(mapRegion)]).then(([v,s,a,l])=>{setVillages(v);setSafeSites(s);setAlerts(a);setLiveFeed(l)}).finally(()=>setLoading(false));const timer=window.setInterval(()=>{refreshLive();api.alerts.list().then(setAlerts).catch(()=>{})},60000);return()=>window.clearInterval(timer)},[mapRegion]);
 const states=INDIA_STATES; const dataRegion=state; const districts=useMemo(()=>state?Array.from(new Set(villages.filter(v=>v.state===state).map(v=>v.district))).sort():[],[villages,state]);
 const filtered=useMemo(()=>villages.filter(v=>(state?v.state===state:INDIA_STATES.includes(v.state))&&(!district||v.district===district)&&(!level||v.level===level)),[villages,state,district,level]);
 const regionSites=useMemo(()=>safeSites.filter(s=>state?s.region===state:INDIA_STATES.includes(s.region||"")),[safeSites,state]);const priorityVillage=useMemo(()=>[...filtered].sort((a,b)=>b.risk_score-a.risk_score)[0],[filtered]);
 const regionAlerts=useMemo(()=>alerts.filter(a=>filtered.some(v=>v.id===a.village_id)),[alerts,filtered]);
 const regionLive=liveFeed.items||[];
 const liveCritical=regionLive.filter(h=>h.severity==="CRITICAL").length;const liveHigh=regionLive.filter(h=>h.severity==="HIGH").length;const liveFires=regionLive.filter(h=>h.type.toLowerCase().includes("fire")).length;const liveQuakes=regionLive.filter(h=>h.type.toLowerCase().includes("earthquake")).length;
 useEffect(()=>{let c=false;setRegionBestSite(null);if(priorityVillage)api.safeSites.rankFor(priorityVillage.id).then(x=>{if(!c)setRegionBestSite(x[0]||null)}).catch(()=>{});return()=>{c=true}},[priorityVillage?.id]);
 useEffect(()=>{if(district&&!districts.includes(district))setDistrict("")},[district,districts]);
 useEffect(()=>{if(state)api.live.news(district?`${district}, ${state}`:state).then(x=>setNews(x.articles||[])).catch(()=>setNews([]));else setNews([])},[state,district]);
 async function handleSelect(v:Village){setSelectedId(v.id);try{const[d,p]=await Promise.all([api.villages.get(v.id),api.relocation.plan(v.id)]);setDetail(d);setPlan(p)}catch{setDetail(null);setPlan(null)}}
 function changeCountry(v:string){setCountry(v);setStateValue("");setDistrict("");setSelectedId(null);setDetail(null);setPlan(null);localStorage.setItem("rakshasetu_region",v)}
 function changeState(v:string){setStateValue(v);setDistrict("");setSelectedId(null);setDetail(null);setPlan(null);if(v)localStorage.setItem("rakshasetu_region",v);else localStorage.setItem("rakshasetu_region","India")}
 function mailOfficer(o:typeof OFFICIALS[number],a?:Alert){const subject=a?`[RakshaSetu] ${a.level} alert · ${a.village_name}`:"[RakshaSetu] Regional disaster response alert";const body=a?`RakshaSetu alert\n\nLocation: ${a.village_name}, ${a.district||""}, ${a.state||""}\nLevel: ${a.level}\nRisk score: ${a.risk_score}\nMessage: ${a.message}\nRecommended action: ${a.action||"Review dashboard"}\n\nAdmin/source contact: ${SOURCE_EMAIL}`:`RakshaSetu response notification.\n\nSelected region: ${district||state||"India"}\nAdmin/source contact: ${SOURCE_EMAIL}`;window.location.href=`mailto:${o.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
 const topSites=regionSites.slice(0,5);const critical=filtered.filter(v=>v.level==="CRITICAL").length;const high=filtered.filter(v=>v.level==="HIGH").length;const totalPopulation=filtered.reduce((n,v)=>n+v.population,0);
 const latestLive=[...regionLive].sort((a,b)=>levelRank(a.severity)-levelRank(b.severity)).slice(0,4);
 return <div className="dashboard-page"><section className="dashboard-hero"><div><span className="eyebrow">COMMAND CENTER · INDIA</span><h1>RakshaSetu</h1><p>Live hazard intelligence, risk zones and response decisions for West Bengal, Bihar, Sikkim and Odisha.</p></div><div className="hero-live-badge"><i/>LIVE DATA · 60s</div></section>
 <FilterBar countries={COUNTRIES} country={country} setCountry={changeCountry} states={states} state={state} setState={changeState} districts={districts} district={district} setDistrict={setDistrict} level={level} setLevel={setLevel}/>
 <section className="command-grid"><div className="map-stage">{loading?<div className="map-loading">Loading live response map…</div>:<RiskMap villages={filtered} safeSites={regionSites} liveHazards={regionLive} selectedId={selectedId} onSelectVillage={handleSelect} region={mapRegion} district={district}/>}<div className="map-overlay-title"><strong>{district||state||"India"}</strong><span>{filtered.length?`${filtered.length} risk zones · ${critical} critical · ${high} high`:`Select a state to narrow the operational view`}</span></div><div className="map-legend"><Legend color="var(--risk-critical)" label="Critical"/><Legend color="var(--risk-high)" label="High"/><Legend color="var(--risk-moderate)" label="Moderate"/><Legend color="var(--risk-low)" label="Low"/><Legend color="#20c7ff" label="Safe"/><Legend color="#ff1744" label="Live"/></div></div>
 <aside className="details-stage"><div className="panel-heading"><div><span className="eyebrow">SELECTED AREA</span><h2>{district||state||"India Pilot"}</h2></div><span className="status-dot">LIVE</span></div>{state&&filtered.length&&!selectedId?<RegionDetailsPanel region={dataRegion} district={district} villages={filtered} safeSites={regionSites} recommendedSite={regionBestSite}/>:selectedId?<SelectedAreaPanel village={detail} onViewRelocation={()=>detail&&navigate(`/relocation?village=${detail.id}`)}/>:<div className="region-empty panel"><span className="eyebrow">FOCUS STATES</span><h3>West Bengal · Bihar · Sikkim · Odisha</h3><p>Select a state and district. The map, live feed, alerts, safe sites and history all follow the same scope.</p></div>}</aside></section>
 <section className="live-feed-panel panel"><div className="section-heading"><div><span className="eyebrow">REAL-TIME PUBLIC SIGNALS</span><h2>Live Hazard Feed · {district||state||"India"}</h2></div><button className="module-action" onClick={refreshLive}>Refresh now</button></div><div className="live-kpi-row"><span><b>{regionLive.length}</b><small>live signals</small></span><span><b>{liveQuakes}</b><small>earthquakes</small></span><span><b>{liveFires}</b><small>fire hotspots</small></span><span><b>{liveCritical}</b><small>critical</small></span><span><b>{liveHigh}</b><small>high</small></span></div><div className="live-source-row">{liveFeed.sources.map(s=><span key={s.name} className={s.status==="live"?"source-live":"source-muted"}><i/>{s.name} · {s.status}{s.count!=null?` · ${s.count}`:""}</span>)}<span className="live-updated">Updated {liveFeed.updated_at?new Date(liveFeed.updated_at).toLocaleTimeString():"—"}</span></div><div className="live-event-grid">{latestLive.map(h=><article className={`live-event-card live-event-${h.severity.toLowerCase()}`} key={h.id}><div><span>{h.type}</span><b>{h.severity}</b></div><strong>{h.title||"Live hazard observation"}</strong><p>{h.detail||"Public real-time observation"}</p><small>{h.lat.toFixed(3)}°, {h.lng.toFixed(3)}° · {h.source}</small></article>)}{!latestLive.length&&<div className="live-empty">No live hazard signal currently inside the selected region. The feed is still polling.</div>}</div></section>
 {state&&<RegionHistoryPanel region={dataRegion} district={district}/>} 
 <section className="dashboard-modules"><div className="section-heading"><div><span className="eyebrow">RESPONSE OPERATIONS</span><h2>{state?`${district||state} Operations`:"Four-State Pilot Operations"}</h2></div></div>
 {topSites.length>0&&<div className="dashboard-inline-section"><div className="inline-title"><h3>Relocation & Safe Sites</h3><span>{regionSites.length} in scope</span></div><div className="safe-site-strip">{topSites.map(s=><article className="safe-site-card" key={s.id}><span className="safe-pill">SAFE SITE</span><strong>{s.name}</strong><small>{s.region}</small><span>Available <b>{s.available_capacity.toLocaleString()}</b></span><span>{s.facilities.slice(0,3).join(" · ")}</span></article>)}{regionSites.length>5&&<article className="safe-site-more">+{regionSites.length-5}<small>more</small></article>}</div></div>}
 {priorityVillage&&<div className="dashboard-inline-section relocation-inline"><div className="inline-title"><h3>Priority Relocation</h3><span>{priorityVillage.level} risk</span></div><div className="priority-relocation"><div><strong>{priorityVillage.name}</strong><span>{priorityVillage.district}, {priorityVillage.state} · Population {priorityVillage.population.toLocaleString()}</span></div><button className="btn" onClick={()=>navigate(`/relocation?village=${priorityVillage.id}`)}>Plan relocation</button></div></div>}
 <div className="operation-card-grid"><article className="operation-card alert-card"><span className="eyebrow">LIVE ALERTS</span><h3>Alert Center</h3><strong>{regionAlerts.length} active signals</strong><p>{regionAlerts.filter(a=>a.level==="CRITICAL").length} critical · {regionAlerts.filter(a=>a.level==="HIGH").length} high</p>{regionAlerts.slice(0,3).map(a=><div className="mini-row" key={`${a.village_id}-${a.level}`}><div><b>{a.level}</b><strong>{a.village_name}</strong><small>{a.district}, {a.state}</small></div><button className="contact-chip" onClick={()=>mailOfficer(OFFICIALS[0],a)}>Notify</button></div>)}{!regionAlerts.length&&<div className="mini-row"><span>No active model alerts in this scope.</span></div>}<button className="btn secondary" onClick={()=>navigate("/alerts")}>Open full alert desk</button></article><article className="operation-card"><span className="eyebrow">PAST INCIDENTS</span><h3>{state?`${state} History`:"Select a state"}</h3><strong>{news.length?`${news.length} current article results`:"Regional incident context"}</strong><p>Current publisher results for the selected state/district.</p>{news.slice(0,3).map((a,i)=><a className="news-row" href={a.url} target="_blank" rel="noreferrer" key={`${a.url}-${i}`}>{a.title}</a>)}{state&&<a className="news-row" href={`https://www.youtube.com/results?search_query=${encodeURIComponent(`${district||state} disaster incident`)}`} target="_blank" rel="noreferrer">YouTube event coverage →</a>}</article><article className="operation-card"><span className="eyebrow">ANALYTICS</span><h3>{state||"Four-state"} Risk Analytics</h3><strong>{filtered.length} locations</strong><p>Critical {critical} · High {high} · Population {totalPopulation.toLocaleString()}</p><div className="analytics-stat-row"><span><small>Critical share</small><b>{filtered.length?Math.round(critical*100/filtered.length):0}%</b></span><span><small>High-risk pop.</small><b>{filtered.filter(v=>v.level==="CRITICAL"||v.level==="HIGH").reduce((n,v)=>n+v.population,0).toLocaleString()}</b></span></div><div className="risk-meter"><i style={{width:`${Math.min(100,critical*100/Math.max(1,filtered.length))}%`,background:"var(--risk-critical)"}}/></div></article><article className="operation-card"><span className="eyebrow">AI DECISION SUPPORT</span><h3>RakshaSetu AI</h3><strong>{state?`Ask about ${state}`:"Ask about the pilot"}</strong><p>Use the selected live region context for risk, relocation, safe sites and incidents.</p><button className="btn" onClick={()=>navigate("/assistant")}>Ask AI</button></article></div>
 <div className="dashboard-inline-section officer-inline"><div className="inline-title"><h3>Officer Alert Desk</h3><span>Direct email / SMS composer</span></div><div className="dashboard-officer-grid">{OFFICIALS.map(o=><article key={o.email}><div><strong>{o.name}</strong><small>{o.email}</small><small>{o.phone}</small></div><button className="contact-chip" onClick={()=>mailOfficer(o)}>Email</button></article>)}</div><p className="data-note">Source/admin contact: {SOURCE_EMAIL}. Actions open the device composer; automated sending requires an authenticated provider.</p></div>
 </section>
 {detail&&<section className="detail-workspace"><div className="section-heading"><div><span className="eyebrow">ZONE INTELLIGENCE</span><h2>{detail.name}</h2></div><span>{detail.district}, {detail.state}</span></div><div className="detail-grid"><PopulationProfile village={detail}/><HazardBars village={detail}/><RainfallTrendChart village={detail}/><HistoryTimeline village={detail}/>{plan&&<RelocationBox plan={plan} onViewRoute={()=>navigate(`/relocation?village=${detail.id}`)}/>}</div></section>}
 <button className="floating-assistant" onClick={()=>navigate("/assistant")} aria-label="Open RakshaSetu AI Assistant"><span className="assistant-orb">AI</span><span><strong>RakshaSetu</strong><small>AI Assistant</small></span></button></div>}
function Legend({color,label}:{color:string;label:string}){return <span className="legend-item"><i style={{background:color}}/>{label}</span>}
