import { useEffect, useMemo, useState } from "react";
import { api } from "../../services/api";
import type { SafeSite } from "../../types";
const REGIONS=["All regions","West Bengal","Bihar","Sikkim","Odisha"];
export default function SafeSites(){
 const [sites,setSites]=useState<SafeSite[]>([]);const [region,setRegion]=useState(()=>localStorage.getItem("rakshasetu_region")||"All regions");
 useEffect(()=>{api.safeSites.list().then(setSites)},[]);
 const visibleSites=useMemo(()=>region==="All regions"?sites:sites.filter(s=>s.region===region),[sites,region]);const totalCapacity=visibleSites.reduce((n,s)=>n+s.capacity,0);const availableCapacity=visibleSites.reduce((n,s)=>n+s.available_capacity,0);
 return <div className="page-shell"><div className="page-hero"><div><span className="eyebrow">EVACUATION INFRASTRUCTURE</span><h2>Safe Sites</h2><p>Capacity, occupancy, infrastructure and hazard exposure for the selected region.</p></div><select value={region} onChange={e=>{setRegion(e.target.value);if(e.target.value!=="All regions")localStorage.setItem("rakshasetu_region",e.target.value)}}>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></div><div className="alert-summary-strip"><span><b>{visibleSites.length}</b><small>safe sites</small></span><span><b>{totalCapacity.toLocaleString()}</b><small>total capacity</small></span><span><b>{availableCapacity.toLocaleString()}</b><small>available now</small></span><span><b>{totalCapacity?Math.round((availableCapacity/totalCapacity)*100):0}%</b><small>free capacity</small></span></div><div className="safe-site-page-grid">{visibleSites.map(s=>{const occupancyPct=s.capacity?Math.min(100,Math.round(s.current_occupancy/s.capacity*100)):0;return <article className="safe-site-detail-card" key={s.id}><div className="safe-site-detail-head"><div><span className="safe-pill">SAFE SITE</span><h3>{s.name}</h3><small>{s.region} · {s.lat.toFixed(4)}, {s.lng.toFixed(4)}</small></div><strong>{s.available_capacity.toLocaleString()}<small> available</small></strong></div><div className="safe-metric-grid"><span><small>Capacity</small><b>{s.capacity.toLocaleString()}</b></span><span><small>Occupancy</small><b>{occupancyPct}%</b></span><span><small>Hazard risk</small><b>{s.hazard_risk}/100</b></span><span><small>Infrastructure</small><b>{s.infrastructure_score}/100</b></span></div><div className="safe-occupancy"><div><small>Current occupancy</small><b>{s.current_occupancy.toLocaleString()} / {s.capacity.toLocaleString()}</b></div><i><em style={{width:`${occupancyPct}%`}}/></i></div><div className="safe-facilities">{s.facilities.map(f=><span key={f}>{f}</span>)}</div></article>})}{!visibleSites.length&&<div className="panel empty-state">No safe sites available for {region}.</div>}</div></div>;
}
