import { useEffect, useMemo, useState } from "react";
import { api } from "../../services/api";
import type { SafeSite } from "../../types";
const REGIONS=["All regions","West Bengal","Bihar","Sikkim","Odisha"];
const value=(v:number|null|undefined)=>v==null?"Not available":v.toLocaleString();
export default function SafeSites(){
 const [sites,setSites]=useState<SafeSite[]>([]);const [region,setRegion]=useState(()=>localStorage.getItem("rakshasetu_region")||"All regions");
 useEffect(()=>{api.safeSites.list(region==="All regions"?undefined:region).then(setSites).catch(()=>setSites([]))},[region]);
 const visibleSites=useMemo(()=>region==="All regions"?sites:sites.filter(s=>s.region===region),[sites,region]);
 const knownCapacity=visibleSites.filter(s=>s.capacity!=null).reduce((n,s)=>n+(s.capacity||0),0);const knownAvailable=visibleSites.filter(s=>s.available_capacity!=null).reduce((n,s)=>n+(s.available_capacity||0),0);
 return <div className="page-shell"><div className="page-hero"><div><span className="eyebrow">MAPPED EMERGENCY INFRASTRUCTURE</span><h2>Relocation Centres</h2><p>Real shelter locations mapped from OpenStreetMap. Operational capacity and occupancy are never estimated.</p></div><select value={region} onChange={e=>{setRegion(e.target.value);if(e.target.value!=="All regions")localStorage.setItem("rakshasetu_region",e.target.value)}}>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></div><div className="alert-summary-strip"><span><b>{visibleSites.length}</b><small>mapped shelters</small></span><span><b>{knownCapacity?knownCapacity.toLocaleString():"—"}</b><small>verified capacity</small></span><span><b>{knownAvailable?knownAvailable.toLocaleString():"—"}</b><small>verified availability</small></span><span><b>OSM</b><small>open source</small></span></div><div className="safe-site-page-grid">{visibleSites.map(s=><article className="safe-site-detail-card" key={s.id}><div className="safe-site-detail-head"><div><span className="safe-pill">MAPPED SHELTER</span><h3>{s.name}</h3><small>{s.region} · {s.lat.toFixed(4)}, {s.lng.toFixed(4)}</small></div><strong>{value(s.available_capacity)}<small> availability</small></strong></div><div className="safe-metric-grid"><span><small>Capacity</small><b>{value(s.capacity)}</b></span><span><small>Occupancy</small><b>{value(s.current_occupancy)}</b></span><span><small>Hazard risk</small><b>{value(s.hazard_risk)}</b></span><span><small>Infrastructure</small><b>{value(s.infrastructure_score)}</b></span></div><div className="safe-facilities">{s.facilities.length?s.facilities.map(f=><span key={f}>{f}</span>):<span>Operational details not published in OSM</span>}</div><div style={{marginTop:10,fontSize:9,color:"var(--text-muted)"}}>{s.note} · <a href={s.source_url} target="_blank" rel="noreferrer">OpenStreetMap source</a></div></article>)}{!visibleSites.length&&<div className="panel empty-state">No mapped emergency shelters found in the selected region.</div>}</div></div>;
}
