import { useEffect,useState } from "react";
import { useSearchParams } from "react-router-dom";
import RiskMap from "../../components/map/RiskMap";
import { api } from "../../services/api";
import type { Village,SafeSite,RelocationPlan } from "../../types";
import "./relocation.css";

export default function Relocation(){
 const [searchParams,setSearchParams]=useSearchParams();
 const selectedRegion=localStorage.getItem("rakshasetu_region")||""; const selectedCity=localStorage.getItem("rakshasetu_city")||""; const selectedDistrict=localStorage.getItem("rakshasetu_district")||"";
 const [villages,setVillages]=useState<Village[]>([]),[sites,setSites]=useState<SafeSite[]>([]),[plan,setPlan]=useState<RelocationPlan|null>(null),[route,setRoute]=useState<any>(null);
 const [villageId,setVillageId]=useState(searchParams.get("village")||""),[selectedSite,setSelectedSite]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!selectedRegion||!selectedDistrict){setLoading(false);setError("Select State / UT → City → District on the dashboard first.");return;} Promise.all([api.villages.list({state:selectedRegion,district:selectedDistrict}),api.safeSites.list({state:selectedRegion,district:selectedDistrict})]).then(([v,s])=>{setVillages(v);setSites(s);if(!villageId&&v.length)setVillageId(v[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[selectedRegion,selectedDistrict]);
 useEffect(()=>{if(!villageId||!selectedRegion||!selectedDistrict)return;setPlan(null);setRoute(null);setSelectedSite("");api.relocation.plan(villageId,{state:selectedRegion,district:selectedDistrict}).then(setPlan).catch(e=>setError(e.message))},[villageId,selectedRegion,selectedDistrict]);
 const selectedVillage=villages.find(v=>v.id===villageId);
 async function handleRoute(siteId:string){if(!villageId)return;setSelectedSite(siteId);setError("");try{setRoute(await api.relocation.route(villageId,siteId,{state:selectedRegion,district:selectedDistrict}))}catch(e){setError(e instanceof Error?e.message:"Road route unavailable")}}
 if(loading)return <div className="scrollable" style={{padding:24}}>Loading live relocation data…</div>;
 return <div className="relocation-command"><div className="relocation-map"><RiskMap villages={selectedVillage?[selectedVillage]:villages} safeSites={sites} selectedId={villageId} route={route?.path} center={selectedVillage?[selectedVillage.lat,selectedVillage.lng]:undefined}/></div><div className="relocation-panel"><div className="panel-heading"><div><span className="eyebrow">LIVE OPEN DATA</span><h2>Guided Relocation</h2></div><span className="status-dot">LIVE</span></div>
 {error&&<div className="relocation-error">{error}</div>}
 {selectedVillage&&<><label className="relocation-select"><span>DANGER / ORIGIN LOCATION · {selectedRegion}</span><select value={villageId} onChange={e=>{setVillageId(e.target.value);setSearchParams({village:e.target.value})}}>{villages.map(v=><option key={v.id} value={v.id}>{v.name} · {v.district||selectedDistrict} · {v.level}</option>)}</select></label><div className="relocation-context"><b>{selectedVillage.name}</b><span>{selectedVillage.district||selectedDistrict}, {selectedVillage.state||selectedRegion} · {selectedCity||"Selected city"}</span><span>Live indicator {selectedVillage.risk_score} · Population {selectedVillage.population==null?"not published":selectedVillage.population.toLocaleString()}</span></div></>}
 <div className="panel" style={{padding:14,marginTop:12}}><span className="eyebrow">4-STEP GUIDED FLOW</span><div className="route-steps"><div><b>01</b><span>Confirm danger location</span></div><div><b>02</b><span>Choose a mapped safe site</span></div><div><b>03</b><span>Generate a live road-network route</span></div><div><b>04</b><span>Follow navigation and official instructions</span></div></div></div>
 <div className="panel" style={{padding:14,marginTop:12}}><h4>Nearby mapped safe sites</h4><p style={{marginTop:6}}>Sites are ranked by geographic distance only. Capacity, occupancy and operating status remain unverified unless the source publishes them.</p>{(plan?.ranked_sites||[]).slice(0,8).map((s:any,i:number)=><div className="ranking-row" key={s.site_id} style={{marginTop:8}}><div><strong>{i+1}. {s.site_name}</strong><small>{s.distance_km} km · {s.verified?"source-verified":"mapped, operational status unverified"}</small></div><button className="contact-chip" onClick={()=>handleRoute(s.site_id)}>{selectedSite===s.site_id?"Route loaded":"Route"}</button></div>)}{!plan?.ranked_sites?.length&&<p style={{marginTop:8}}>No mapped emergency shelter was returned for this district.</p>}</div>
 {route&&<div className="panel route-card"><span className="eyebrow">{route.route_available?"ROAD ROUTE":"ENDPOINT ROUTE"}</span><h3>{route.from.name} → {route.to.name}</h3><div className="route-metrics"><span><b>{route.road_distance_km??"—"} km</b><small>road distance</small></span><span><b>{route.road_eta_minutes!=null?`${route.road_eta_minutes} min`:"—"}</b><small>road ETA</small></span><span><b>{route.air_distance_km??"—"} km</b><small>point-to-point</small></span><span><b>{route.router??"—"}</b><small>routing source</small></span></div>{route.steps?.length>0&&<div className="guided-instructions"><strong>Route steps</strong>{route.steps.map((s:any,i:number)=><div key={i}><b>{i+1}</b><span>{s.instruction}<small>{s.distance_km} km · {s.duration_minutes} min</small></span></div>)}</div>}<div className="route-actions"><a className="btn" href={route.google_maps_driving_url} target="_blank" rel="noreferrer">Open Google Maps · Road</a></div><p>{route.note}</p></div>}
 </div></div>;
}
