import { useEffect,useMemo,useState } from "react";
import { useSearchParams } from "react-router-dom";
import RiskMap from "../../components/map/RiskMap";
import { api } from "../../services/api";
import type { Village,SafeSite } from "../../types";
import "./relocation.css";
const PILOT=["West Bengal","Bihar","Sikkim","Odisha"];
export default function Relocation(){
 const [searchParams,setSearchParams]=useSearchParams(); const selectedRegion=localStorage.getItem("rakshasetu_region")||"Bihar"; const [villages,setVillages]=useState<Village[]>([]); const [sites,setSites]=useState<SafeSite[]>([]); const [villageId,setVillageId]=useState(searchParams.get("village")||""); const [route,setRoute]=useState<any>(null); const [selectedSite,setSelectedSite]=useState<string>(""); const [error,setError]=useState("");
 useEffect(()=>{Promise.all([api.villages.list({}),api.safeSites.list()]).then(([v,s])=>{const regional=v.filter(x=>PILOT.includes(x.state||"")&&(!selectedRegion||selectedRegion==="India"||x.state===selectedRegion));const regionalSites=s.filter(x=>!x.region||selectedRegion==="India"||x.region===selectedRegion);setVillages(regional);setSites(regionalSites);if(!villageId&&regional.length)setVillageId(regional[0].id);}).catch(()=>setError("Could not load live relocation data."))},[]);
 const selectedVillage=villages.find(v=>v.id===villageId); const regionalSites=useMemo(()=>selectedVillage?sites.filter(s=>!s.region||s.region===selectedVillage.state):sites,[sites,selectedVillage]);
 async function handleViewRoute(siteId:string){if(!villageId)return;setSelectedSite(siteId);setError("");try{setRoute(await api.relocation.route(villageId,siteId))}catch{setError("Road route is unavailable for these live endpoints.")}}
 return <div className="relocation-command"><div className="relocation-map"><RiskMap villages={selectedVillage?[selectedVillage]:villages} safeSites={regionalSites} selectedId={villageId} route={route?.path} center={selectedVillage?[selectedVillage.lat,selectedVillage.lng]:undefined}/></div><div className="relocation-panel"><div className="panel-heading"><div><span className="eyebrow">LIVE OPEN DATA</span><h2>Relocation support</h2></div><span className="status-dot">LIVE</span></div><label className="relocation-select"><span>{selectedRegion.toUpperCase()} · SELECT SETTLEMENT</span><select value={villageId} onChange={e=>{setVillageId(e.target.value);setSearchParams({village:e.target.value});setRoute(null)}}>{villages.map(v=><option key={v.id} value={v.id}>{v.name} · {v.district||"mapped"} · {v.level}</option>)}</select></label>{selectedVillage&&<div className="relocation-context"><b>{selectedVillage.name}</b><span>{selectedVillage.district||"Mapped settlement"}, {selectedVillage.state||"India"}</span><span>Coordinates · {selectedVillage.lat.toFixed(5)}°, {selectedVillage.lng.toFixed(5)}° · Population {selectedVillage.population==null?"not published":selectedVillage.population.toLocaleString()} · Live indicator {selectedVillage.risk_score}</span></div>}{error&&<div className="relocation-error">{error}</div>}<div className="panel" style={{padding:14,marginTop:12}}><h4>Mapped relocation centres</h4><p style={{marginTop:6}}>These are real OpenStreetMap shelter records. Capacity, occupancy and operating status are intentionally shown as unavailable unless a verified operational source publishes them.</p>{regionalSites.slice(0,12).map(s=><div className="ranking-row" key={s.id} style={{marginTop:8}}><div><strong>{s.name}</strong><small>{s.lat.toFixed(4)}, {s.lng.toFixed(4)} · capacity {s.capacity==null?"not published":s.capacity.toLocaleString()}</small></div><button className="contact-chip" onClick={()=>handleViewRoute(s.id)}>{selectedSite===s.id?"Selected":"Route"}</button></div>)}{!regionalSites.length&&<p style={{marginTop:8}}>No mapped emergency shelters were returned for this region.</p>}</div>{route&&<div className="panel route-card"><span className="eyebrow">{route.route_available?"ROAD ROUTE":"ENDPOINT ROUTE"}</span><h3>{route.from.name} → {route.to.name}</h3><div className="route-metrics"><span><b>{route.road_distance_km??"—"} km</b><small>road distance</small></span><span><b>{route.road_eta_minutes!=null?`${route.road_eta_minutes} min`:"—"}</b><small>road ETA</small></span><span><b>{route.air_distance_km??"—"} km</b><small>point-to-point</small></span><span><b>{route.router??"—"}</b><small>routing source</small></span></div><div className="route-actions"><a className="btn" href={route.google_maps_driving_url} target="_blank" rel="noreferrer">Open Google Maps · Road</a></div><p>{route.note}</p></div>}</div></div>;
}
