import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import RiskMap from "../../components/map/RiskMap";
import RelocationBox from "../../components/relocation/RelocationBox";
import { api } from "../../services/api";
import type { Village, SafeSite, RelocationPlan } from "../../types";
import "./relocation.css";
const PILOT=["West Bengal","Bihar","Sikkim","Odisha"];
export default function Relocation(){
 const [searchParams,setSearchParams]=useSearchParams();const selectedRegion=localStorage.getItem("rakshasetu_region")||"Bihar";const [villages,setVillages]=useState<Village[]>([]);const [sites,setSites]=useState<SafeSite[]>([]);const [villageId,setVillageId]=useState(searchParams.get("village")||"");const [plan,setPlan]=useState<RelocationPlan|null>(null);const [route,setRoute]=useState<any>(null);const [routeLoading,setRouteLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{Promise.all([api.villages.list(),api.safeSites.list()]).then(([v,s])=>{const regional=v.filter(x=>PILOT.includes(x.state)&&(!selectedRegion||x.state===selectedRegion));const regionalSites=s.filter(x=>!x.region||x.region===selectedRegion);setVillages(regional);setSites(regionalSites);if(!villageId&&regional.length)setVillageId(regional[0].id);}).catch(()=>setError("Could not load relocation data."))},[]);
 useEffect(()=>{if(!villageId)return;setSearchParams({village:villageId});setRoute(null);setError("");api.relocation.plan(villageId).then(setPlan).catch(()=>setError("Could not generate a relocation recommendation."))},[villageId,setSearchParams]);
 const selectedVillage=villages.find(v=>v.id===villageId);const regionalSites=useMemo(()=>selectedVillage?sites.filter(s=>!s.region||s.region===selectedVillage.state):sites,[sites,selectedVillage]);
 async function handleViewRoute(siteId:string){if(!villageId)return;setRouteLoading(true);setError("");try{setRoute(await api.relocation.route(villageId,siteId))}catch{setError("Route could not be generated. Try another safe site.")}finally{setRouteLoading(false)}}
 return <div className="relocation-command"><div className="relocation-map"><RiskMap villages={selectedVillage?[selectedVillage]:villages} safeSites={regionalSites} selectedId={villageId} route={route?.path} center={selectedVillage?[selectedVillage.lat,selectedVillage.lng]:undefined}/></div><div className="relocation-panel"><div className="panel-heading"><div><span className="eyebrow">EVACUATION COMMAND</span><h2>Safe relocation</h2></div><span className="status-dot">LIVE</span></div><label className="relocation-select"><span>{selectedRegion.toUpperCase()} · SELECT ZONE</span><select value={villageId} onChange={e=>setVillageId(e.target.value)}>{villages.map(v=><option key={v.id} value={v.id}>{v.name} · {v.district} · {v.level}</option>)}</select></label>{selectedVillage&&<div className="relocation-context"><b>{selectedVillage.district}, {selectedVillage.state}</b><span>Population {selectedVillage.population.toLocaleString()} · Risk {selectedVillage.risk_score}</span></div>}{error&&<div className="relocation-error">{error}</div>}{plan&&<RelocationBox plan={plan} onViewRoute={handleViewRoute}/>} {routeLoading&&<div className="panel route-status">Fetching road-network route…</div>}{route&&<div className="panel route-card"><span className="eyebrow">LIVE ROUTE</span><h3>{route.from.name} → {route.to.name}</h3><div className="route-metrics"><span><b>{route.road_distance_km} km</b><small>road distance</small></span><span><b>{route.road_eta_minutes!=null?`${route.road_eta_minutes} min`:`Open Maps`}</b><small>road ETA</small></span><span><b>{route.air_distance_km} km</b><small>air distance</small></span></div><div className="route-actions"><a className="btn" href={route.google_maps_driving_url} target="_blank" rel="noreferrer">Google Maps · Road</a><a className="btn secondary" href={route.google_maps_transit_url} target="_blank" rel="noreferrer">Google Maps · Transit</a></div><p>{route.note}</p></div>}{plan&&plan.ranked_sites.length>0&&<div className="panel ranking-panel"><h4>SITE SUITABILITY · BEST FIRST</h4>{plan.ranked_sites.map((s,i)=><div className="ranking-row" key={s.site_id}><div><strong>{i+1}. {s.site_name}</strong><small>{s.distance_km} km · {s.road_access} access · {s.available_capacity.toLocaleString()} free</small></div><b>{s.suitability}/100</b><button className="contact-chip" onClick={()=>handleViewRoute(s.site_id)}>Route</button></div>)}</div>}</div></div>;
}
