import type { Village,VillageDetail,SafeSite,RelocationPlan,Alert,RiskSummary,LiveHazardFeed } from "../types";
const BASE_URL=import.meta.env.VITE_API_BASE_URL||"http://localhost:8000";
const savedScope=()=>localStorage.getItem("rakshasetu_region")||"";
const savedDistrict=()=>localStorage.getItem("rakshasetu_district")||"";
const savedCity=()=>localStorage.getItem("rakshasetu_city")||"";
async function request<T>(path:string,init?:RequestInit):Promise<T>{const res=await fetch(`${BASE_URL}${path}`,{headers:{"Content-Type":"application/json"},...init});if(!res.ok)throw new Error(`API ${res.status}: ${await res.text()}`);return res.json()}
export const api={
 regions:{states:()=>request<any[]>("/api/regions/states"),districts:(state:string)=>request<any[]>(`/api/regions/districts?state=${encodeURIComponent(state)}`),cities:(state:string,district?:string)=>request<any[]>(`/api/regions/cities?state=${encodeURIComponent(state)}${district?`&district=${encodeURIComponent(district)}`:""}`)},
 villages:{list:(p?:{state?:string;region?:string;district?:string;level?:string})=>{const q=new URLSearchParams();const s=p?.state||p?.region||savedScope(),d=p?.district||(p?savedDistrict():savedDistrict());if(s&&s!=="India")q.set("state",s);if(d)q.set("district",d);if(p?.level)q.set("level",p.level);return request<Village[]>(`/api/villages${q.toString()?`?${q}`:""}`)},get:(id:string,p?:{state?:string;district?:string})=>{const q=new URLSearchParams();const s=p?.state||savedScope(),d=p?.district||savedDistrict();if(s)q.set("state",s);if(d)q.set("district",d);return request<VillageDetail>(`/api/villages/${id}${q.toString()?`?${q}`:""}`)}},
 safeSites:{list:(p?:{state?:string;region?:string;district?:string})=>{const q=new URLSearchParams();const s=p?.state||p?.region||savedScope(),d=p?.district||savedDistrict();if(s&&s!=="India")q.set("state",s);if(d)q.set("district",d);return request<SafeSite[]>(`/api/safesites${q.toString()?`?${q}`:""}`)},rankFor:(id:string)=>request<any>(`/api/safesites/rank-for/${id}`)},
 relocation:{plan:(id:string,p?:{state?:string;district?:string})=>request<RelocationPlan>(`/api/relocation/plan/${id}?region=${encodeURIComponent(p?.state||savedScope())}&district=${encodeURIComponent(p?.district||savedDistrict())}`),allPlans:()=>request<any[]>("/api/relocation/plans"),route:(v:string,s:string,p?:{state?:string;district?:string})=>request<any>(`/api/relocation/route/${v}/${s}?region=${encodeURIComponent(p?.state||savedScope())}&district=${encodeURIComponent(p?.district||savedDistrict())}`)},
 alerts:{list:(p?:{state?:string;district?:string})=>request<Alert[]>(`/api/alerts${p?.state?`?state=${encodeURIComponent(p.state)}${p.district?`&district=${encodeURIComponent(p.district)}`:""}`:""}`),summary:()=>request<Record<string,number>>("/api/alerts/summary")},
 risk:{summary:(state?:string,district?:string)=>request<RiskSummary>(`/api/risk/summary${state?`?region=${encodeURIComponent(state)}${district?`&district=${encodeURIComponent(district)}`:""}`:""}`)},
 history:{get:(id:string)=>request<any>(`/api/history/${id}`),region:(region:string,district?:string)=>request<any>(`/api/history/region/${encodeURIComponent(region)}${district?`?district=${encodeURIComponent(district)}`:""}`)},
 reports:{overview:(region?:string)=>request<any>(`/api/reports/overview${region?`?region=${encodeURIComponent(region)}`:""}`)},
 live:{hazards:(region?:string,district?:string)=>request<LiveHazardFeed>(`/api/live/hazards${region?`?region=${encodeURIComponent(region)}${district?`&district=${encodeURIComponent(district)}`:""}`:""}`),news:(region:string,district?:string)=>request<any>(`/api/live/news?region=${encodeURIComponent(region)}${district?`&district=${encodeURIComponent(district)}`:""}`)},
 assistant:{ask:(question:string)=>request<any>("/api/assistant",{method:"POST",body:JSON.stringify({question})})}
};
export{savedScope,savedDistrict,savedCity};
