import { MapContainer, TileLayer, CircleMarker, Tooltip, Popup, Polyline, useMap, LayersControl } from "react-leaflet";
import { useEffect } from "react";
import L from "leaflet";
import "leaflet/dist/leaflet.css";
import "./risk-map.css";
import type { Village, SafeSite } from "../../types";
interface LiveHazard { id:string; type:string; title?:string; lat:number; lng:number; magnitude?:number; severity:string; source:string; url?:string }
interface RiskMapProps { villages:Village[]; safeSites?:SafeSite[]; liveHazards?:LiveHazard[]; selectedId?:string|null; onSelectVillage?:(v:Village)=>void; region?:string; district?:string; route?:[number,number][]; center?:[number,number]; zoom?:number }
type View={center:[number,number];zoom:number};
const REGION_VIEWS:Record<string,View>={India:{center:[22.6,79],zoom:5},Nepal:{center:[28.3,84.2],zoom:7},China:{center:[35.8,103.8],zoom:4},"West Bengal":{center:[23.9,87.8],zoom:7},Bihar:{center:[25.9,85.7],zoom:7},Odisha:{center:[20.4,84.4],zoom:7},Jharkhand:{center:[23.6,85.3],zoom:7},Sikkim:{center:[27.6,88.5],zoom:9},Koshi:{center:[27.2,87],zoom:8},Madhesh:{center:[26.7,85.7],zoom:8},Bagmati:{center:[27.9,85.3],zoom:8},Gandaki:{center:[28.3,84.3],zoom:8},Lumbini:{center:[27.9,83.4],zoom:8},Karnali:{center:[29.2,82.5],zoom:7},Sudurpashchim:{center:[29.3,80.5],zoom:7},Anhui:{center:[31.8,117.2],zoom:7},Beijing:{center:[40,116.4],zoom:9},Chongqing:{center:[29.5,106.5],zoom:8},Guangdong:{center:[23.4,113.4],zoom:7},Gansu:{center:[38,99],zoom:6},Sichuan:{center:[30.6,102],zoom:7},Yunnan:{center:[25,101.5],zoom:7},Tibet:{center:[31,88],zoom:5},Xinjiang:{center:[41.7,85],zoom:5}};
function Viewport({villages,region,district,route}:{villages:Village[];region?:string;district?:string;route?:[number,number][]}){const map=useMap();useEffect(()=>{map.invalidateSize({animate:false});const points=route?.length?route:villages.map(v=>[v.lat,v.lng] as [number,number]);if(district&&points.length){const b=L.latLngBounds(points);if(b.isValid()){map.fitBounds(b,{padding:[55,55],maxZoom:12,animate:true,duration:.65});return}}const view=REGION_VIEWS[region||""];if(view){map.setView(view.center,view.zoom,{animate:true,duration:.65});return}if(points.length&&region){const b=L.latLngBounds(points);if(b.isValid())map.fitBounds(b,{padding:[45,45],maxZoom:9,animate:true,duration:.65});return}map.setView([25.4,86],5,{animate:false})},[map,villages,region,district,route]);return null}
export default function RiskMap({villages,safeSites=[],liveHazards=[],selectedId,onSelectVillage,region,district,route,center=[25.4,86],zoom=6}:RiskMapProps){const view=REGION_VIEWS[region||""];const satelliteDate=new Date(Date.now()-86400000).toISOString().slice(0,10);return <MapContainer center={view?.center||center} zoom={view?.zoom||zoom} minZoom={3} maxZoom={18} scrollWheelZoom zoomControl doubleClickZoom dragging touchZoom style={{height:"100%",width:"100%"}} preferCanvas><Viewport villages={villages} region={region} district={district} route={route}/><LayersControl position="topright"><LayersControl.BaseLayer checked name="Street map"><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" maxZoom={19} keepBuffer={2} updateWhenIdle updateWhenZooming={false}/></LayersControl.BaseLayer><LayersControl.Overlay name="Near-real-time satellite"><TileLayer url={`https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/${satelliteDate}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`} opacity={.88} maxZoom={9}/></LayersControl.Overlay></LayersControl>{villages.map(v=>{const selected=v.id===selectedId;const radius=selected?20:Math.max(8,Math.min(18,7+v.risk_score/9));return <CircleMarker key={v.id} center={[v.lat,v.lng]} radius={radius} className={`risk-pulse risk-pulse-${v.level.toLowerCase()}`} pathOptions={{color:v.color,fillColor:v.color,fillOpacity:selected?.92:.72,weight:selected?3:2}} eventHandlers={{click:()=>onSelectVillage?.(v)}}><Tooltip direction="top" offset={[0,-8]}><strong>{v.name}</strong><br/>{v.district}, {v.state}<br/><b>Risk {v.risk_score} · {v.level}</b><br/>Population {v.population.toLocaleString()}</Tooltip></CircleMarker>})}{liveHazards.map(h=><CircleMarker key={`live-${h.id}`} center={[h.lat,h.lng]} radius={h.severity==="CRITICAL"?15:11} className={`live-hazard live-${h.severity.toLowerCase()}`} pathOptions={{color:h.severity==="CRITICAL"?"#b91c1c":"#ea580c",fillColor:h.severity==="CRITICAL"?"#ef4444":"#fb923c",fillOpacity:.8,weight:2}}><Popup><strong>LIVE · {h.type}</strong><br/>{h.title||"Live hazard observation"}{h.magnitude!=null?<><br/>Magnitude {h.magnitude}</>:null}<br/>Source: {h.source}{h.url?<><br/><a href={h.url} target="_blank" rel="noreferrer">Source details</a></>:null}</Popup></CircleMarker>)}{safeSites.map(s=><CircleMarker key={s.id} center={[s.lat,s.lng]} radius={9} className="safe-pulse" pathOptions={{color:"#075985",fillColor:"#38bdf8",fillOpacity:.9,weight:2}}><Popup><strong>{s.name}</strong><br/>SAFE SITE · Available {s.available_capacity.toLocaleString()}<br/>Facilities: {s.facilities.slice(0,4).join(", ")}</Popup></CircleMarker>)}{route?.length?<Polyline positions={route} pathOptions={{color:"#2563eb",weight:5,opacity:.9,dashArray:"10 8"}}/>:null}</MapContainer>}
