import { useEffect,useState } from "react";
import { api } from "../../services/api";
import type { LiveHazardFeed } from "../../types";
import AlertsSummary from "../../components/alerts/AlertsSummary";

export default function Alerts(){
 const [feed,setFeed]=useState<LiveHazardFeed>({updated_at:"",items:[],sources:[]});const[state,setState]=useState(()=>localStorage.getItem("rakshasetu_region")||"");const[district,setDistrict]=useState(()=>localStorage.getItem("rakshasetu_district")||"");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function refresh(){if(!state){setError("Select a State / UT on the dashboard first.");return}setLoading(true);setError("");try{setFeed(await api.live.hazards(state,district||undefined))}catch(e){setError(e instanceof Error?e.message:"Live alert feed unavailable")}finally{setLoading(false)}}
 useEffect(()=>{refresh();const id=window.setInterval(refresh,60000);return()=>window.clearInterval(id)},[state,district]);
 const alerts=feed.items||[];const critical=alerts.filter(a=>a.severity==="CRITICAL");const high=alerts.filter(a=>a.severity==="HIGH");
 return <div className="page-shell"><div className="page-hero"><div><span className="eyebrow">REAL-TIME PUBLIC SIGNALS</span><h2>Alerts & Response</h2><p>Live observations and official public alerts for the selected State / UT and District.</p></div><div className="page-hero-actions"><span className="mono">{district||state||"No scope selected"}</span><button className="module-action" onClick={refresh}>{loading?"Refreshing…":"Refresh"}</button></div></div>
 {error&&<div className="panel" style={{padding:16,marginBottom:16}}>{error}</div>}
 <div className="alert-layout"><main><div className="alert-summary-strip"><span><b>{alerts.length}</b><small>live signals</small></span><span><b>{critical.length}</b><small>critical</small></span><span><b>{high.length}</b><small>high</small></span><span><b>{alerts.filter(a=>a.type.toLowerCase().includes("earthquake")).length}</b><small>earthquakes</small></span></div><div className="alert-list">{!alerts.length&&!loading&&<div className="panel empty-state">No public hazard signal was returned for {district||state||"the selected scope"}.</div>}{alerts.map((a,i)=><article key={`${a.id}-${i}`} className="alert-detail-card"><div className="alert-card-head"><span className="alert-level-pill">{a.severity}</span><span className="mono">{a.type}</span></div><h3>{a.title||"Live hazard observation"}</h3><div className="alert-location"><strong>{district||state||"Selected scope"}</strong><span>{a.source}</span><span className="mono">{a.lat!=null&&a.lng!=null?`${a.lat.toFixed(4)}, ${a.lng.toFixed(4)}`:"Source did not publish coordinates"}</span></div><p>{a.detail||"Public real-time observation."}</p><div className="alert-action-row"><span><small>SOURCE</small><b>{a.source}</b></span><span><small>OBSERVED</small><b>{a.time?new Date(a.time).toLocaleString():"—"}</b></span></div>{a.url&&<a className="btn secondary" href={a.url} target="_blank" rel="noreferrer">Open source details</a>}</article>)}</div></main><aside><AlertsSummary alerts={alerts.map(a=>({village_id:a.id,village_name:a.title||a.type,level:a.severity==="LOW"?"WARNING":a.severity,risk_score:a.severity==="CRITICAL"?100:a.severity==="HIGH"?75:a.severity==="MODERATE"?50:25,message:a.detail||"Public source observation",source:a.source}))}/></aside></div>
 <section className="officer-panel panel"><div className="section-heading"><div><span className="eyebrow">DATA PROVENANCE</span><h2>Live source status</h2></div><span className="mono">UPDATED {feed.updated_at?new Date(feed.updated_at).toLocaleTimeString():"—"}</span></div><div className="officer-grid">{feed.sources.map(s=><article className="officer-card" key={s.name}><div><strong>{s.name}</strong><small>Status: {s.status}</small><small>{s.count!=null?`${s.count} records`:"No count published"}</small></div></article>)}</div><p className="data-note">These are public observations and official feeds. They do not replace government evacuation instructions.</p></section>
 </div>;
}
