import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { api } from "../../services/api";
import type { Alert } from "../../types";
import AlertsSummary from "../../components/alerts/AlertsSummary";

const LEVEL_STYLE: Record<string, { color: string }> = { CRITICAL: { color: "var(--risk-critical)" }, HIGH: { color: "var(--risk-high)" }, WARNING: { color: "var(--risk-moderate)" } };
const OFFICIALS = [
 { name:"Anushko Adhikary", email:"anushkoadhikary8918@gmail.com", phone:"8918552039" },
 { name:"Medha Mallick", email:"medha.mallick2020@gmail.com", phone:"9007564988" },
 { name:"Ayan Acharya", email:"ayanacharya06@gmail.com", phone:"9433172520" },
 { name:"Soumyadeep Palit", email:"soumyadeeppalit546@gmail.com", phone:"8697453997" },
 { name:"Prithiwi Barui", email:"prithiwibarui@gmail.com", phone:"9748069930" }
];
const SOURCE_EMAIL="mishravinit923@gmail.com";
export default function Alerts(){
 const [alerts,setAlerts]=useState<Alert[]>([]);const [soundOn,setSoundOn]=useState(false);const [region,setRegion]=useState(()=>localStorage.getItem("rakshasetu_region")||"India");
 async function refresh(){try{setAlerts(await api.alerts.list())}catch{setAlerts([])}}
 useEffect(()=>{refresh();const id=window.setInterval(refresh,30000);return()=>window.clearInterval(id)},[]);
 const scoped=useMemo(()=>region&&region!=="India"?alerts.filter(a=>a.state===region):alerts,[alerts,region]);const critical=scoped.filter(a=>a.level==="CRITICAL");const high=scoped.filter(a=>a.level==="HIGH");
 function testSiren(){const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return;const ctx=new A();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type="sawtooth";gain.gain.value=.035;osc.frequency.value=720;osc.start();window.setTimeout(()=>osc.frequency.value=420,450);window.setTimeout(()=>{osc.stop();ctx.close()},900);setSoundOn(true);window.setTimeout(()=>setSoundOn(false),1000)}
 function mailOfficer(o:typeof OFFICIALS[number],a?:Alert){const subject=a?`[RakshaSetu] ${a.level} alert · ${a.village_name}`:"[RakshaSetu] Disaster response alert";const body=a?`RakshaSetu alert\n\nLocation: ${a.village_name}, ${a.district||""}, ${a.state||""}\nCoordinates: ${a.lat?.toFixed(5)||"—"}, ${a.lng?.toFixed(5)||"—"}\nLevel: ${a.level}\nRisk score: ${a.risk_score}\nPopulation: ${a.population?.toLocaleString()||"—"}\nMessage: ${a.message}\nRecommended action: ${a.action||"Review dashboard"}\nSource: ${a.source||"RakshaSetu"}\n\nAdmin/source contact: ${SOURCE_EMAIL}`:`RakshaSetu response notification.\n\nSelected region: ${region}\nAdmin/source contact: ${SOURCE_EMAIL}`;window.location.href=`mailto:${o.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
 function smsOfficer(o:typeof OFFICIALS[number],a?:Alert){const body=a?`RakshaSetu ${a.level}: ${a.village_name}, ${a.district||""}, ${a.state||""}. Risk ${a.risk_score}. ${a.message}`:`RakshaSetu response notification: review active alerts for ${region}.`;window.location.href=`sms:${o.phone}?body=${encodeURIComponent(body)}`}
 return <div className="page-shell"><div className="page-hero"><div><span className="eyebrow">INCIDENT ESCALATION</span><h2>Alerts & Response</h2><p>Every alert now carries the exact monitored location, district, state, risk score and response action.</p></div><div className="page-hero-actions"><select value={region} onChange={e=>setRegion(e.target.value)}><option>India</option><option>West Bengal</option><option>Bihar</option><option>Sikkim</option><option>Odisha</option></select><button className="module-action" onClick={refresh}>Refresh</button></div></div>
 {critical.length>0&&<div className="critical-alert-banner"><span className="pulse-dot"/><div><strong>{critical.length} CRITICAL ALERT{critical.length>1?"S":""}</strong><span>{high.length} high-priority signals · immediate officer review recommended.</span></div><button onClick={testSiren}>{soundOn?"SIREN ACTIVE":"TEST SIREN"}</button></div>}
 <div className="alert-layout"><main><div className="alert-summary-strip"><span><b>{scoped.length}</b><small>active</small></span><span><b>{critical.length}</b><small>critical</small></span><span><b>{high.length}</b><small>high</small></span><span><b>{scoped.filter(a=>a.level==="WARNING").length}</b><small>capacity warnings</small></span></div><div className="alert-list">{scoped.length===0&&<div className="panel empty-state">No active alerts in {region}.</div>}{scoped.map((a,i)=>{const style=LEVEL_STYLE[a.level]||LEVEL_STYLE.WARNING;return <article key={`${a.village_id}-${a.level}-${i}`} className="alert-detail-card" style={{"--alert-color":style.color} as CSSProperties}><div className="alert-card-head"><span className="alert-level-pill">{a.level}</span><span className="mono">RISK {a.risk_score}</span></div><h3>{a.village_name}</h3><div className="alert-location"><strong>{a.district||"District unavailable"}</strong><span>{a.state||"State unavailable"}</span><span className="mono">{a.lat?.toFixed(4)||"—"}, {a.lng?.toFixed(4)||"—"}</span></div><p>{a.message}</p><div className="alert-action-row"><span><small>ACTION</small><b>{a.action||"Review dashboard"}</b></span><span><small>POPULATION</small><b>{a.population?.toLocaleString()||"—"}</b></span><span><small>SOURCE</small><b>{a.source||"Risk engine"}</b></span></div><div className="alert-contact-row">{OFFICIALS.slice(0,3).map(o=><button key={o.email} className="contact-chip" onClick={()=>mailOfficer(o,a)}>Notify {o.name.split(" ")[0]}</button>)}</div></article>})}</div></main><aside><AlertsSummary alerts={scoped}/></aside></div>
 <section className="officer-panel panel"><div className="section-heading"><div><span className="eyebrow">ADMINISTRATION CONTACTS</span><h2>Officer Alert Desk</h2></div><span className="mono">FROM {SOURCE_EMAIL}</span></div><div className="officer-grid">{OFFICIALS.map(o=><article className="officer-card" key={o.email}><div><span className="officer-avatar">{o.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><strong>{o.name}</strong><small>{o.email}</small><small>{o.phone}</small></div><div className="officer-buttons"><button className="btn" onClick={()=>mailOfficer(o)}>Email</button><button className="btn secondary" onClick={()=>smsOfficer(o)}>SMS</button></div></article>)}</div><p className="data-note">Email/SMS opens the device composer. Automated sending requires an authenticated notification provider.</p></section>
 </div>;
}
